// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transfer.proto

package com.znjt.proto;

/**
 * Protobuf enum {@code com.znjt.proto.DataType}
 */
public enum DataType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>T_INI = 0;</code>
   */
  T_INI(0),
  /**
   * <code>T_GPS = 1;</code>
   */
  T_GPS(1),
  /**
   * <code>T_GPS_SINGLE = 2;</code>
   */
  T_GPS_SINGLE(2),
  /**
   * <code>T_GPS_SINGLE_TEST = 3;</code>
   */
  T_GPS_SINGLE_TEST(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>T_INI = 0;</code>
   */
  public static final int T_INI_VALUE = 0;
  /**
   * <code>T_GPS = 1;</code>
   */
  public static final int T_GPS_VALUE = 1;
  /**
   * <code>T_GPS_SINGLE = 2;</code>
   */
  public static final int T_GPS_SINGLE_VALUE = 2;
  /**
   * <code>T_GPS_SINGLE_TEST = 3;</code>
   */
  public static final int T_GPS_SINGLE_TEST_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DataType valueOf(int value) {
    return forNumber(value);
  }

  public static DataType forNumber(int value) {
    switch (value) {
      case 0: return T_INI;
      case 1: return T_GPS;
      case 2: return T_GPS_SINGLE;
      case 3: return T_GPS_SINGLE_TEST;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DataType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DataType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
          public DataType findValueByNumber(int number) {
            return DataType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.znjt.proto.TransferProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final DataType[] VALUES = values();

  public static DataType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DataType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.znjt.proto.DataType)
}

