// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transfer.proto

package com.znjt.proto;

/**
 * Protobuf type {@code com.znjt.proto.GPSRecord}
 */
public  final class GPSRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.znjt.proto.GPSRecord)
    GPSRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GPSRecord.newBuilder() to construct.
  private GPSRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GPSRecord() {
    clientRecordId_ = "";
    dataId_ = "";
    servOpsRes_ = false;
    imgData_ = java.util.Collections.emptyList();
    fileErr_ = false;
    lostedSize_ = 0;
    fileNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GPSRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientRecordId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dataId_ = s;
            break;
          }
          case 24: {

            servOpsRes_ = input.readBool();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              imgData_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000008;
            }
            imgData_.add(input.readBytes());
            break;
          }
          case 40: {

            fileErr_ = input.readBool();
            break;
          }
          case 48: {

            lostedSize_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              fileNames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000040;
            }
            fileNames_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        imgData_ = java.util.Collections.unmodifiableList(imgData_);
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        fileNames_ = fileNames_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.znjt.proto.GPSRecord.class, com.znjt.proto.GPSRecord.Builder.class);
  }

  private int bitField0_;
  public static final int CLIENT_RECORD_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientRecordId_;
  /**
   * <code>string client_record_id = 1;</code>
   */
  public java.lang.String getClientRecordId() {
    java.lang.Object ref = clientRecordId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientRecordId_ = s;
      return s;
    }
  }
  /**
   * <code>string client_record_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClientRecordIdBytes() {
    java.lang.Object ref = clientRecordId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientRecordId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATAID_FIELD_NUMBER = 2;
  private volatile java.lang.Object dataId_;
  /**
   * <code>string dataId = 2;</code>
   */
  public java.lang.String getDataId() {
    java.lang.Object ref = dataId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataId_ = s;
      return s;
    }
  }
  /**
   * <code>string dataId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDataIdBytes() {
    java.lang.Object ref = dataId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERV_OPS_RES_FIELD_NUMBER = 3;
  private boolean servOpsRes_;
  /**
   * <code>bool serv_ops_res = 3;</code>
   */
  public boolean getServOpsRes() {
    return servOpsRes_;
  }

  public static final int IMG_DATA_FIELD_NUMBER = 4;
  private java.util.List<com.google.protobuf.ByteString> imgData_;
  /**
   * <code>repeated bytes img_data = 4;</code>
   */
  public java.util.List<com.google.protobuf.ByteString>
      getImgDataList() {
    return imgData_;
  }
  /**
   * <code>repeated bytes img_data = 4;</code>
   */
  public int getImgDataCount() {
    return imgData_.size();
  }
  /**
   * <code>repeated bytes img_data = 4;</code>
   */
  public com.google.protobuf.ByteString getImgData(int index) {
    return imgData_.get(index);
  }

  public static final int FILE_ERR_FIELD_NUMBER = 5;
  private boolean fileErr_;
  /**
   * <code>bool file_err = 5;</code>
   */
  public boolean getFileErr() {
    return fileErr_;
  }

  public static final int LOSTED_SIZE_FIELD_NUMBER = 6;
  private int lostedSize_;
  /**
   * <code>int32 losted_size = 6;</code>
   */
  public int getLostedSize() {
    return lostedSize_;
  }

  public static final int FILE_NAMES_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList fileNames_;
  /**
   * <code>repeated string file_names = 7;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getFileNamesList() {
    return fileNames_;
  }
  /**
   * <code>repeated string file_names = 7;</code>
   */
  public int getFileNamesCount() {
    return fileNames_.size();
  }
  /**
   * <code>repeated string file_names = 7;</code>
   */
  public java.lang.String getFileNames(int index) {
    return fileNames_.get(index);
  }
  /**
   * <code>repeated string file_names = 7;</code>
   */
  public com.google.protobuf.ByteString
      getFileNamesBytes(int index) {
    return fileNames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientRecordIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientRecordId_);
    }
    if (!getDataIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dataId_);
    }
    if (servOpsRes_ != false) {
      output.writeBool(3, servOpsRes_);
    }
    for (int i = 0; i < imgData_.size(); i++) {
      output.writeBytes(4, imgData_.get(i));
    }
    if (fileErr_ != false) {
      output.writeBool(5, fileErr_);
    }
    if (lostedSize_ != 0) {
      output.writeInt32(6, lostedSize_);
    }
    for (int i = 0; i < fileNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, fileNames_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientRecordIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientRecordId_);
    }
    if (!getDataIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dataId_);
    }
    if (servOpsRes_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, servOpsRes_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < imgData_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(imgData_.get(i));
      }
      size += dataSize;
      size += 1 * getImgDataList().size();
    }
    if (fileErr_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, fileErr_);
    }
    if (lostedSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, lostedSize_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < fileNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(fileNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFileNamesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.znjt.proto.GPSRecord)) {
      return super.equals(obj);
    }
    com.znjt.proto.GPSRecord other = (com.znjt.proto.GPSRecord) obj;

    boolean result = true;
    result = result && getClientRecordId()
        .equals(other.getClientRecordId());
    result = result && getDataId()
        .equals(other.getDataId());
    result = result && (getServOpsRes()
        == other.getServOpsRes());
    result = result && getImgDataList()
        .equals(other.getImgDataList());
    result = result && (getFileErr()
        == other.getFileErr());
    result = result && (getLostedSize()
        == other.getLostedSize());
    result = result && getFileNamesList()
        .equals(other.getFileNamesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENT_RECORD_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientRecordId().hashCode();
    hash = (37 * hash) + DATAID_FIELD_NUMBER;
    hash = (53 * hash) + getDataId().hashCode();
    hash = (37 * hash) + SERV_OPS_RES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getServOpsRes());
    if (getImgDataCount() > 0) {
      hash = (37 * hash) + IMG_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getImgDataList().hashCode();
    }
    hash = (37 * hash) + FILE_ERR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFileErr());
    hash = (37 * hash) + LOSTED_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getLostedSize();
    if (getFileNamesCount() > 0) {
      hash = (37 * hash) + FILE_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getFileNamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.znjt.proto.GPSRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.GPSRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.GPSRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.GPSRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.GPSRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.GPSRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.GPSRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.znjt.proto.GPSRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.znjt.proto.GPSRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.znjt.proto.GPSRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.znjt.proto.GPSRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.znjt.proto.GPSRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.znjt.proto.GPSRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.znjt.proto.GPSRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.znjt.proto.GPSRecord)
      com.znjt.proto.GPSRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.znjt.proto.GPSRecord.class, com.znjt.proto.GPSRecord.Builder.class);
    }

    // Construct using com.znjt.proto.GPSRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientRecordId_ = "";

      dataId_ = "";

      servOpsRes_ = false;

      imgData_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      fileErr_ = false;

      lostedSize_ = 0;

      fileNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSRecord_descriptor;
    }

    @java.lang.Override
    public com.znjt.proto.GPSRecord getDefaultInstanceForType() {
      return com.znjt.proto.GPSRecord.getDefaultInstance();
    }

    @java.lang.Override
    public com.znjt.proto.GPSRecord build() {
      com.znjt.proto.GPSRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.znjt.proto.GPSRecord buildPartial() {
      com.znjt.proto.GPSRecord result = new com.znjt.proto.GPSRecord(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.clientRecordId_ = clientRecordId_;
      result.dataId_ = dataId_;
      result.servOpsRes_ = servOpsRes_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        imgData_ = java.util.Collections.unmodifiableList(imgData_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.imgData_ = imgData_;
      result.fileErr_ = fileErr_;
      result.lostedSize_ = lostedSize_;
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        fileNames_ = fileNames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.fileNames_ = fileNames_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.znjt.proto.GPSRecord) {
        return mergeFrom((com.znjt.proto.GPSRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.znjt.proto.GPSRecord other) {
      if (other == com.znjt.proto.GPSRecord.getDefaultInstance()) return this;
      if (!other.getClientRecordId().isEmpty()) {
        clientRecordId_ = other.clientRecordId_;
        onChanged();
      }
      if (!other.getDataId().isEmpty()) {
        dataId_ = other.dataId_;
        onChanged();
      }
      if (other.getServOpsRes() != false) {
        setServOpsRes(other.getServOpsRes());
      }
      if (!other.imgData_.isEmpty()) {
        if (imgData_.isEmpty()) {
          imgData_ = other.imgData_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureImgDataIsMutable();
          imgData_.addAll(other.imgData_);
        }
        onChanged();
      }
      if (other.getFileErr() != false) {
        setFileErr(other.getFileErr());
      }
      if (other.getLostedSize() != 0) {
        setLostedSize(other.getLostedSize());
      }
      if (!other.fileNames_.isEmpty()) {
        if (fileNames_.isEmpty()) {
          fileNames_ = other.fileNames_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureFileNamesIsMutable();
          fileNames_.addAll(other.fileNames_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.znjt.proto.GPSRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.znjt.proto.GPSRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object clientRecordId_ = "";
    /**
     * <code>string client_record_id = 1;</code>
     */
    public java.lang.String getClientRecordId() {
      java.lang.Object ref = clientRecordId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientRecordId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_record_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientRecordIdBytes() {
      java.lang.Object ref = clientRecordId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientRecordId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_record_id = 1;</code>
     */
    public Builder setClientRecordId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientRecordId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_record_id = 1;</code>
     */
    public Builder clearClientRecordId() {
      
      clientRecordId_ = getDefaultInstance().getClientRecordId();
      onChanged();
      return this;
    }
    /**
     * <code>string client_record_id = 1;</code>
     */
    public Builder setClientRecordIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientRecordId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dataId_ = "";
    /**
     * <code>string dataId = 2;</code>
     */
    public java.lang.String getDataId() {
      java.lang.Object ref = dataId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataIdBytes() {
      java.lang.Object ref = dataId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataId = 2;</code>
     */
    public Builder setDataId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataId = 2;</code>
     */
    public Builder clearDataId() {
      
      dataId_ = getDefaultInstance().getDataId();
      onChanged();
      return this;
    }
    /**
     * <code>string dataId = 2;</code>
     */
    public Builder setDataIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataId_ = value;
      onChanged();
      return this;
    }

    private boolean servOpsRes_ ;
    /**
     * <code>bool serv_ops_res = 3;</code>
     */
    public boolean getServOpsRes() {
      return servOpsRes_;
    }
    /**
     * <code>bool serv_ops_res = 3;</code>
     */
    public Builder setServOpsRes(boolean value) {
      
      servOpsRes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool serv_ops_res = 3;</code>
     */
    public Builder clearServOpsRes() {
      
      servOpsRes_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> imgData_ = java.util.Collections.emptyList();
    private void ensureImgDataIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        imgData_ = new java.util.ArrayList<com.google.protobuf.ByteString>(imgData_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated bytes img_data = 4;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getImgDataList() {
      return java.util.Collections.unmodifiableList(imgData_);
    }
    /**
     * <code>repeated bytes img_data = 4;</code>
     */
    public int getImgDataCount() {
      return imgData_.size();
    }
    /**
     * <code>repeated bytes img_data = 4;</code>
     */
    public com.google.protobuf.ByteString getImgData(int index) {
      return imgData_.get(index);
    }
    /**
     * <code>repeated bytes img_data = 4;</code>
     */
    public Builder setImgData(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImgDataIsMutable();
      imgData_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes img_data = 4;</code>
     */
    public Builder addImgData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImgDataIsMutable();
      imgData_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes img_data = 4;</code>
     */
    public Builder addAllImgData(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureImgDataIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, imgData_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes img_data = 4;</code>
     */
    public Builder clearImgData() {
      imgData_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private boolean fileErr_ ;
    /**
     * <code>bool file_err = 5;</code>
     */
    public boolean getFileErr() {
      return fileErr_;
    }
    /**
     * <code>bool file_err = 5;</code>
     */
    public Builder setFileErr(boolean value) {
      
      fileErr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool file_err = 5;</code>
     */
    public Builder clearFileErr() {
      
      fileErr_ = false;
      onChanged();
      return this;
    }

    private int lostedSize_ ;
    /**
     * <code>int32 losted_size = 6;</code>
     */
    public int getLostedSize() {
      return lostedSize_;
    }
    /**
     * <code>int32 losted_size = 6;</code>
     */
    public Builder setLostedSize(int value) {
      
      lostedSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 losted_size = 6;</code>
     */
    public Builder clearLostedSize() {
      
      lostedSize_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList fileNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFileNamesIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        fileNames_ = new com.google.protobuf.LazyStringArrayList(fileNames_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <code>repeated string file_names = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFileNamesList() {
      return fileNames_.getUnmodifiableView();
    }
    /**
     * <code>repeated string file_names = 7;</code>
     */
    public int getFileNamesCount() {
      return fileNames_.size();
    }
    /**
     * <code>repeated string file_names = 7;</code>
     */
    public java.lang.String getFileNames(int index) {
      return fileNames_.get(index);
    }
    /**
     * <code>repeated string file_names = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFileNamesBytes(int index) {
      return fileNames_.getByteString(index);
    }
    /**
     * <code>repeated string file_names = 7;</code>
     */
    public Builder setFileNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFileNamesIsMutable();
      fileNames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string file_names = 7;</code>
     */
    public Builder addFileNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFileNamesIsMutable();
      fileNames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string file_names = 7;</code>
     */
    public Builder addAllFileNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureFileNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fileNames_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string file_names = 7;</code>
     */
    public Builder clearFileNames() {
      fileNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string file_names = 7;</code>
     */
    public Builder addFileNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFileNamesIsMutable();
      fileNames_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.znjt.proto.GPSRecord)
  }

  // @@protoc_insertion_point(class_scope:com.znjt.proto.GPSRecord)
  private static final com.znjt.proto.GPSRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.znjt.proto.GPSRecord();
  }

  public static com.znjt.proto.GPSRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GPSRecord>
      PARSER = new com.google.protobuf.AbstractParser<GPSRecord>() {
    @java.lang.Override
    public GPSRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GPSRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GPSRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GPSRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.znjt.proto.GPSRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

