// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transfer.proto

package com.znjt.proto;

public interface GPSRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.znjt.proto.GPSRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_record_id = 1;</code>
   */
  java.lang.String getClientRecordId();
  /**
   * <code>string client_record_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientRecordIdBytes();

  /**
   * <code>string dataId = 2;</code>
   */
  java.lang.String getDataId();
  /**
   * <code>string dataId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataIdBytes();

  /**
   * <code>bool serv_ops_res = 3;</code>
   */
  boolean getServOpsRes();

  /**
   * <code>repeated bytes img_data = 4;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getImgDataList();
  /**
   * <code>repeated bytes img_data = 4;</code>
   */
  int getImgDataCount();
  /**
   * <code>repeated bytes img_data = 4;</code>
   */
  com.google.protobuf.ByteString getImgData(int index);

  /**
   * <code>bool file_err = 5;</code>
   */
  boolean getFileErr();

  /**
   * <code>int32 losted_size = 6;</code>
   */
  int getLostedSize();

  /**
   * <code>repeated string file_names = 7;</code>
   */
  java.util.List<java.lang.String>
      getFileNamesList();
  /**
   * <code>repeated string file_names = 7;</code>
   */
  int getFileNamesCount();
  /**
   * <code>repeated string file_names = 7;</code>
   */
  java.lang.String getFileNames(int index);
  /**
   * <code>repeated string file_names = 7;</code>
   */
  com.google.protobuf.ByteString
      getFileNamesBytes(int index);
}
