// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transfer.proto

package com.znjt.proto;

/**
 * Protobuf type {@code com.znjt.proto.GPSSingleRecord}
 */
public  final class GPSSingleRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.znjt.proto.GPSSingleRecord)
    GPSSingleRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GPSSingleRecord.newBuilder() to construct.
  private GPSSingleRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GPSSingleRecord() {
    clientRecordId_ = "";
    dataId_ = "";
    servOpsRes_ = false;
    imgData_ = com.google.protobuf.ByteString.EMPTY;
    fileErr_ = false;
    fileName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GPSSingleRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientRecordId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dataId_ = s;
            break;
          }
          case 24: {

            servOpsRes_ = input.readBool();
            break;
          }
          case 34: {

            imgData_ = input.readBytes();
            break;
          }
          case 40: {

            fileErr_ = input.readBool();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            fileName_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSSingleRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSSingleRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.znjt.proto.GPSSingleRecord.class, com.znjt.proto.GPSSingleRecord.Builder.class);
  }

  public static final int CLIENT_RECORD_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientRecordId_;
  /**
   * <code>string client_record_id = 1;</code>
   */
  public java.lang.String getClientRecordId() {
    java.lang.Object ref = clientRecordId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientRecordId_ = s;
      return s;
    }
  }
  /**
   * <code>string client_record_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClientRecordIdBytes() {
    java.lang.Object ref = clientRecordId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientRecordId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATAID_FIELD_NUMBER = 2;
  private volatile java.lang.Object dataId_;
  /**
   * <code>string dataId = 2;</code>
   */
  public java.lang.String getDataId() {
    java.lang.Object ref = dataId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataId_ = s;
      return s;
    }
  }
  /**
   * <code>string dataId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDataIdBytes() {
    java.lang.Object ref = dataId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERV_OPS_RES_FIELD_NUMBER = 3;
  private boolean servOpsRes_;
  /**
   * <code>bool serv_ops_res = 3;</code>
   */
  public boolean getServOpsRes() {
    return servOpsRes_;
  }

  public static final int IMG_DATA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString imgData_;
  /**
   * <code>bytes img_data = 4;</code>
   */
  public com.google.protobuf.ByteString getImgData() {
    return imgData_;
  }

  public static final int FILE_ERR_FIELD_NUMBER = 5;
  private boolean fileErr_;
  /**
   * <code>bool file_err = 5;</code>
   */
  public boolean getFileErr() {
    return fileErr_;
  }

  public static final int FILE_NAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object fileName_;
  /**
   * <code>string file_name = 6;</code>
   */
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string file_name = 6;</code>
   */
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientRecordIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientRecordId_);
    }
    if (!getDataIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dataId_);
    }
    if (servOpsRes_ != false) {
      output.writeBool(3, servOpsRes_);
    }
    if (!imgData_.isEmpty()) {
      output.writeBytes(4, imgData_);
    }
    if (fileErr_ != false) {
      output.writeBool(5, fileErr_);
    }
    if (!getFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fileName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientRecordIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientRecordId_);
    }
    if (!getDataIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dataId_);
    }
    if (servOpsRes_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, servOpsRes_);
    }
    if (!imgData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, imgData_);
    }
    if (fileErr_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, fileErr_);
    }
    if (!getFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fileName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.znjt.proto.GPSSingleRecord)) {
      return super.equals(obj);
    }
    com.znjt.proto.GPSSingleRecord other = (com.znjt.proto.GPSSingleRecord) obj;

    boolean result = true;
    result = result && getClientRecordId()
        .equals(other.getClientRecordId());
    result = result && getDataId()
        .equals(other.getDataId());
    result = result && (getServOpsRes()
        == other.getServOpsRes());
    result = result && getImgData()
        .equals(other.getImgData());
    result = result && (getFileErr()
        == other.getFileErr());
    result = result && getFileName()
        .equals(other.getFileName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENT_RECORD_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientRecordId().hashCode();
    hash = (37 * hash) + DATAID_FIELD_NUMBER;
    hash = (53 * hash) + getDataId().hashCode();
    hash = (37 * hash) + SERV_OPS_RES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getServOpsRes());
    hash = (37 * hash) + IMG_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getImgData().hashCode();
    hash = (37 * hash) + FILE_ERR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFileErr());
    hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.znjt.proto.GPSSingleRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.GPSSingleRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.GPSSingleRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.GPSSingleRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.GPSSingleRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.GPSSingleRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.GPSSingleRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.znjt.proto.GPSSingleRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.znjt.proto.GPSSingleRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.znjt.proto.GPSSingleRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.znjt.proto.GPSSingleRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.znjt.proto.GPSSingleRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.znjt.proto.GPSSingleRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.znjt.proto.GPSSingleRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.znjt.proto.GPSSingleRecord)
      com.znjt.proto.GPSSingleRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSSingleRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSSingleRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.znjt.proto.GPSSingleRecord.class, com.znjt.proto.GPSSingleRecord.Builder.class);
    }

    // Construct using com.znjt.proto.GPSSingleRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientRecordId_ = "";

      dataId_ = "";

      servOpsRes_ = false;

      imgData_ = com.google.protobuf.ByteString.EMPTY;

      fileErr_ = false;

      fileName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_GPSSingleRecord_descriptor;
    }

    @java.lang.Override
    public com.znjt.proto.GPSSingleRecord getDefaultInstanceForType() {
      return com.znjt.proto.GPSSingleRecord.getDefaultInstance();
    }

    @java.lang.Override
    public com.znjt.proto.GPSSingleRecord build() {
      com.znjt.proto.GPSSingleRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.znjt.proto.GPSSingleRecord buildPartial() {
      com.znjt.proto.GPSSingleRecord result = new com.znjt.proto.GPSSingleRecord(this);
      result.clientRecordId_ = clientRecordId_;
      result.dataId_ = dataId_;
      result.servOpsRes_ = servOpsRes_;
      result.imgData_ = imgData_;
      result.fileErr_ = fileErr_;
      result.fileName_ = fileName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.znjt.proto.GPSSingleRecord) {
        return mergeFrom((com.znjt.proto.GPSSingleRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.znjt.proto.GPSSingleRecord other) {
      if (other == com.znjt.proto.GPSSingleRecord.getDefaultInstance()) return this;
      if (!other.getClientRecordId().isEmpty()) {
        clientRecordId_ = other.clientRecordId_;
        onChanged();
      }
      if (!other.getDataId().isEmpty()) {
        dataId_ = other.dataId_;
        onChanged();
      }
      if (other.getServOpsRes() != false) {
        setServOpsRes(other.getServOpsRes());
      }
      if (other.getImgData() != com.google.protobuf.ByteString.EMPTY) {
        setImgData(other.getImgData());
      }
      if (other.getFileErr() != false) {
        setFileErr(other.getFileErr());
      }
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.znjt.proto.GPSSingleRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.znjt.proto.GPSSingleRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clientRecordId_ = "";
    /**
     * <code>string client_record_id = 1;</code>
     */
    public java.lang.String getClientRecordId() {
      java.lang.Object ref = clientRecordId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientRecordId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_record_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientRecordIdBytes() {
      java.lang.Object ref = clientRecordId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientRecordId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_record_id = 1;</code>
     */
    public Builder setClientRecordId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientRecordId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_record_id = 1;</code>
     */
    public Builder clearClientRecordId() {
      
      clientRecordId_ = getDefaultInstance().getClientRecordId();
      onChanged();
      return this;
    }
    /**
     * <code>string client_record_id = 1;</code>
     */
    public Builder setClientRecordIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientRecordId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dataId_ = "";
    /**
     * <code>string dataId = 2;</code>
     */
    public java.lang.String getDataId() {
      java.lang.Object ref = dataId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataIdBytes() {
      java.lang.Object ref = dataId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataId = 2;</code>
     */
    public Builder setDataId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataId = 2;</code>
     */
    public Builder clearDataId() {
      
      dataId_ = getDefaultInstance().getDataId();
      onChanged();
      return this;
    }
    /**
     * <code>string dataId = 2;</code>
     */
    public Builder setDataIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataId_ = value;
      onChanged();
      return this;
    }

    private boolean servOpsRes_ ;
    /**
     * <code>bool serv_ops_res = 3;</code>
     */
    public boolean getServOpsRes() {
      return servOpsRes_;
    }
    /**
     * <code>bool serv_ops_res = 3;</code>
     */
    public Builder setServOpsRes(boolean value) {
      
      servOpsRes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool serv_ops_res = 3;</code>
     */
    public Builder clearServOpsRes() {
      
      servOpsRes_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString imgData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes img_data = 4;</code>
     */
    public com.google.protobuf.ByteString getImgData() {
      return imgData_;
    }
    /**
     * <code>bytes img_data = 4;</code>
     */
    public Builder setImgData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imgData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes img_data = 4;</code>
     */
    public Builder clearImgData() {
      
      imgData_ = getDefaultInstance().getImgData();
      onChanged();
      return this;
    }

    private boolean fileErr_ ;
    /**
     * <code>bool file_err = 5;</code>
     */
    public boolean getFileErr() {
      return fileErr_;
    }
    /**
     * <code>bool file_err = 5;</code>
     */
    public Builder setFileErr(boolean value) {
      
      fileErr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool file_err = 5;</code>
     */
    public Builder clearFileErr() {
      
      fileErr_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object fileName_ = "";
    /**
     * <code>string file_name = 6;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string file_name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string file_name = 6;</code>
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string file_name = 6;</code>
     */
    public Builder clearFileName() {
      
      fileName_ = getDefaultInstance().getFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string file_name = 6;</code>
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.znjt.proto.GPSSingleRecord)
  }

  // @@protoc_insertion_point(class_scope:com.znjt.proto.GPSSingleRecord)
  private static final com.znjt.proto.GPSSingleRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.znjt.proto.GPSSingleRecord();
  }

  public static com.znjt.proto.GPSSingleRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GPSSingleRecord>
      PARSER = new com.google.protobuf.AbstractParser<GPSSingleRecord>() {
    @java.lang.Override
    public GPSSingleRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GPSSingleRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GPSSingleRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GPSSingleRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.znjt.proto.GPSSingleRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

