// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transfer.proto

package com.znjt.proto;

public interface GPSSingleRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.znjt.proto.GPSSingleRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_record_id = 1;</code>
   */
  java.lang.String getClientRecordId();
  /**
   * <code>string client_record_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientRecordIdBytes();

  /**
   * <code>string dataId = 2;</code>
   */
  java.lang.String getDataId();
  /**
   * <code>string dataId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataIdBytes();

  /**
   * <code>bool serv_ops_res = 3;</code>
   */
  boolean getServOpsRes();

  /**
   * <code>bytes img_data = 4;</code>
   */
  com.google.protobuf.ByteString getImgData();

  /**
   * <code>bool file_err = 5;</code>
   */
  boolean getFileErr();

  /**
   * <code>string file_name = 6;</code>
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 6;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();
}
