// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transfer.proto

package com.znjt.proto;

public interface INIRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.znjt.proto.INIRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_record_id = 1;</code>
   */
  java.lang.String getClientRecordId();
  /**
   * <code>string client_record_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientRecordIdBytes();

  /**
   * <code>string dataId = 2;</code>
   */
  java.lang.String getDataId();
  /**
   * <code>string dataId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataIdBytes();

  /**
   * <code>bool serv_ops_res = 3;</code>
   */
  boolean getServOpsRes();
}
