// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transfer.proto

package com.znjt.proto;

/**
 * Protobuf type {@code com.znjt.proto.SyncMulSingleImgRequest}
 */
public  final class SyncMulSingleImgRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.znjt.proto.SyncMulSingleImgRequest)
    SyncMulSingleImgRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SyncMulSingleImgRequest.newBuilder() to construct.
  private SyncMulSingleImgRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SyncMulSingleImgRequest() {
    dataType_ = 0;
    gpsSingleRecord_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SyncMulSingleImgRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            dataType_ = rawValue;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              gpsSingleRecord_ = new java.util.ArrayList<com.znjt.proto.GPSSingleRecord>();
              mutable_bitField0_ |= 0x00000002;
            }
            gpsSingleRecord_.add(
                input.readMessage(com.znjt.proto.GPSSingleRecord.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        gpsSingleRecord_ = java.util.Collections.unmodifiableList(gpsSingleRecord_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncMulSingleImgRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncMulSingleImgRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.znjt.proto.SyncMulSingleImgRequest.class, com.znjt.proto.SyncMulSingleImgRequest.Builder.class);
  }

  private int bitField0_;
  public static final int DATA_TYPE_FIELD_NUMBER = 1;
  private int dataType_;
  /**
   * <code>.com.znjt.proto.DataType data_type = 1;</code>
   */
  public int getDataTypeValue() {
    return dataType_;
  }
  /**
   * <code>.com.znjt.proto.DataType data_type = 1;</code>
   */
  public com.znjt.proto.DataType getDataType() {
    @SuppressWarnings("deprecation")
    com.znjt.proto.DataType result = com.znjt.proto.DataType.valueOf(dataType_);
    return result == null ? com.znjt.proto.DataType.UNRECOGNIZED : result;
  }

  public static final int GPS_SINGLE_RECORD_FIELD_NUMBER = 2;
  private java.util.List<com.znjt.proto.GPSSingleRecord> gpsSingleRecord_;
  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  public java.util.List<com.znjt.proto.GPSSingleRecord> getGpsSingleRecordList() {
    return gpsSingleRecord_;
  }
  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  public java.util.List<? extends com.znjt.proto.GPSSingleRecordOrBuilder> 
      getGpsSingleRecordOrBuilderList() {
    return gpsSingleRecord_;
  }
  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  public int getGpsSingleRecordCount() {
    return gpsSingleRecord_.size();
  }
  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  public com.znjt.proto.GPSSingleRecord getGpsSingleRecord(int index) {
    return gpsSingleRecord_.get(index);
  }
  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  public com.znjt.proto.GPSSingleRecordOrBuilder getGpsSingleRecordOrBuilder(
      int index) {
    return gpsSingleRecord_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataType_ != com.znjt.proto.DataType.T_INI.getNumber()) {
      output.writeEnum(1, dataType_);
    }
    for (int i = 0; i < gpsSingleRecord_.size(); i++) {
      output.writeMessage(2, gpsSingleRecord_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataType_ != com.znjt.proto.DataType.T_INI.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, dataType_);
    }
    for (int i = 0; i < gpsSingleRecord_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, gpsSingleRecord_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.znjt.proto.SyncMulSingleImgRequest)) {
      return super.equals(obj);
    }
    com.znjt.proto.SyncMulSingleImgRequest other = (com.znjt.proto.SyncMulSingleImgRequest) obj;

    boolean result = true;
    result = result && dataType_ == other.dataType_;
    result = result && getGpsSingleRecordList()
        .equals(other.getGpsSingleRecordList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + dataType_;
    if (getGpsSingleRecordCount() > 0) {
      hash = (37 * hash) + GPS_SINGLE_RECORD_FIELD_NUMBER;
      hash = (53 * hash) + getGpsSingleRecordList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.znjt.proto.SyncMulSingleImgRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.znjt.proto.SyncMulSingleImgRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.znjt.proto.SyncMulSingleImgRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.znjt.proto.SyncMulSingleImgRequest)
      com.znjt.proto.SyncMulSingleImgRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncMulSingleImgRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncMulSingleImgRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.znjt.proto.SyncMulSingleImgRequest.class, com.znjt.proto.SyncMulSingleImgRequest.Builder.class);
    }

    // Construct using com.znjt.proto.SyncMulSingleImgRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGpsSingleRecordFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dataType_ = 0;

      if (gpsSingleRecordBuilder_ == null) {
        gpsSingleRecord_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        gpsSingleRecordBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncMulSingleImgRequest_descriptor;
    }

    @java.lang.Override
    public com.znjt.proto.SyncMulSingleImgRequest getDefaultInstanceForType() {
      return com.znjt.proto.SyncMulSingleImgRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.znjt.proto.SyncMulSingleImgRequest build() {
      com.znjt.proto.SyncMulSingleImgRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.znjt.proto.SyncMulSingleImgRequest buildPartial() {
      com.znjt.proto.SyncMulSingleImgRequest result = new com.znjt.proto.SyncMulSingleImgRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.dataType_ = dataType_;
      if (gpsSingleRecordBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          gpsSingleRecord_ = java.util.Collections.unmodifiableList(gpsSingleRecord_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.gpsSingleRecord_ = gpsSingleRecord_;
      } else {
        result.gpsSingleRecord_ = gpsSingleRecordBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.znjt.proto.SyncMulSingleImgRequest) {
        return mergeFrom((com.znjt.proto.SyncMulSingleImgRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.znjt.proto.SyncMulSingleImgRequest other) {
      if (other == com.znjt.proto.SyncMulSingleImgRequest.getDefaultInstance()) return this;
      if (other.dataType_ != 0) {
        setDataTypeValue(other.getDataTypeValue());
      }
      if (gpsSingleRecordBuilder_ == null) {
        if (!other.gpsSingleRecord_.isEmpty()) {
          if (gpsSingleRecord_.isEmpty()) {
            gpsSingleRecord_ = other.gpsSingleRecord_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureGpsSingleRecordIsMutable();
            gpsSingleRecord_.addAll(other.gpsSingleRecord_);
          }
          onChanged();
        }
      } else {
        if (!other.gpsSingleRecord_.isEmpty()) {
          if (gpsSingleRecordBuilder_.isEmpty()) {
            gpsSingleRecordBuilder_.dispose();
            gpsSingleRecordBuilder_ = null;
            gpsSingleRecord_ = other.gpsSingleRecord_;
            bitField0_ = (bitField0_ & ~0x00000002);
            gpsSingleRecordBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGpsSingleRecordFieldBuilder() : null;
          } else {
            gpsSingleRecordBuilder_.addAllMessages(other.gpsSingleRecord_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.znjt.proto.SyncMulSingleImgRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.znjt.proto.SyncMulSingleImgRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int dataType_ = 0;
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public Builder setDataTypeValue(int value) {
      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public com.znjt.proto.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.znjt.proto.DataType result = com.znjt.proto.DataType.valueOf(dataType_);
      return result == null ? com.znjt.proto.DataType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public Builder setDataType(com.znjt.proto.DataType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dataType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public Builder clearDataType() {
      
      dataType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.znjt.proto.GPSSingleRecord> gpsSingleRecord_ =
      java.util.Collections.emptyList();
    private void ensureGpsSingleRecordIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        gpsSingleRecord_ = new java.util.ArrayList<com.znjt.proto.GPSSingleRecord>(gpsSingleRecord_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.znjt.proto.GPSSingleRecord, com.znjt.proto.GPSSingleRecord.Builder, com.znjt.proto.GPSSingleRecordOrBuilder> gpsSingleRecordBuilder_;

    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public java.util.List<com.znjt.proto.GPSSingleRecord> getGpsSingleRecordList() {
      if (gpsSingleRecordBuilder_ == null) {
        return java.util.Collections.unmodifiableList(gpsSingleRecord_);
      } else {
        return gpsSingleRecordBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public int getGpsSingleRecordCount() {
      if (gpsSingleRecordBuilder_ == null) {
        return gpsSingleRecord_.size();
      } else {
        return gpsSingleRecordBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public com.znjt.proto.GPSSingleRecord getGpsSingleRecord(int index) {
      if (gpsSingleRecordBuilder_ == null) {
        return gpsSingleRecord_.get(index);
      } else {
        return gpsSingleRecordBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public Builder setGpsSingleRecord(
        int index, com.znjt.proto.GPSSingleRecord value) {
      if (gpsSingleRecordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGpsSingleRecordIsMutable();
        gpsSingleRecord_.set(index, value);
        onChanged();
      } else {
        gpsSingleRecordBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public Builder setGpsSingleRecord(
        int index, com.znjt.proto.GPSSingleRecord.Builder builderForValue) {
      if (gpsSingleRecordBuilder_ == null) {
        ensureGpsSingleRecordIsMutable();
        gpsSingleRecord_.set(index, builderForValue.build());
        onChanged();
      } else {
        gpsSingleRecordBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public Builder addGpsSingleRecord(com.znjt.proto.GPSSingleRecord value) {
      if (gpsSingleRecordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGpsSingleRecordIsMutable();
        gpsSingleRecord_.add(value);
        onChanged();
      } else {
        gpsSingleRecordBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public Builder addGpsSingleRecord(
        int index, com.znjt.proto.GPSSingleRecord value) {
      if (gpsSingleRecordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGpsSingleRecordIsMutable();
        gpsSingleRecord_.add(index, value);
        onChanged();
      } else {
        gpsSingleRecordBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public Builder addGpsSingleRecord(
        com.znjt.proto.GPSSingleRecord.Builder builderForValue) {
      if (gpsSingleRecordBuilder_ == null) {
        ensureGpsSingleRecordIsMutable();
        gpsSingleRecord_.add(builderForValue.build());
        onChanged();
      } else {
        gpsSingleRecordBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public Builder addGpsSingleRecord(
        int index, com.znjt.proto.GPSSingleRecord.Builder builderForValue) {
      if (gpsSingleRecordBuilder_ == null) {
        ensureGpsSingleRecordIsMutable();
        gpsSingleRecord_.add(index, builderForValue.build());
        onChanged();
      } else {
        gpsSingleRecordBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public Builder addAllGpsSingleRecord(
        java.lang.Iterable<? extends com.znjt.proto.GPSSingleRecord> values) {
      if (gpsSingleRecordBuilder_ == null) {
        ensureGpsSingleRecordIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, gpsSingleRecord_);
        onChanged();
      } else {
        gpsSingleRecordBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public Builder clearGpsSingleRecord() {
      if (gpsSingleRecordBuilder_ == null) {
        gpsSingleRecord_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        gpsSingleRecordBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public Builder removeGpsSingleRecord(int index) {
      if (gpsSingleRecordBuilder_ == null) {
        ensureGpsSingleRecordIsMutable();
        gpsSingleRecord_.remove(index);
        onChanged();
      } else {
        gpsSingleRecordBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public com.znjt.proto.GPSSingleRecord.Builder getGpsSingleRecordBuilder(
        int index) {
      return getGpsSingleRecordFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public com.znjt.proto.GPSSingleRecordOrBuilder getGpsSingleRecordOrBuilder(
        int index) {
      if (gpsSingleRecordBuilder_ == null) {
        return gpsSingleRecord_.get(index);  } else {
        return gpsSingleRecordBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public java.util.List<? extends com.znjt.proto.GPSSingleRecordOrBuilder> 
         getGpsSingleRecordOrBuilderList() {
      if (gpsSingleRecordBuilder_ != null) {
        return gpsSingleRecordBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(gpsSingleRecord_);
      }
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public com.znjt.proto.GPSSingleRecord.Builder addGpsSingleRecordBuilder() {
      return getGpsSingleRecordFieldBuilder().addBuilder(
          com.znjt.proto.GPSSingleRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public com.znjt.proto.GPSSingleRecord.Builder addGpsSingleRecordBuilder(
        int index) {
      return getGpsSingleRecordFieldBuilder().addBuilder(
          index, com.znjt.proto.GPSSingleRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
     */
    public java.util.List<com.znjt.proto.GPSSingleRecord.Builder> 
         getGpsSingleRecordBuilderList() {
      return getGpsSingleRecordFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.znjt.proto.GPSSingleRecord, com.znjt.proto.GPSSingleRecord.Builder, com.znjt.proto.GPSSingleRecordOrBuilder> 
        getGpsSingleRecordFieldBuilder() {
      if (gpsSingleRecordBuilder_ == null) {
        gpsSingleRecordBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.znjt.proto.GPSSingleRecord, com.znjt.proto.GPSSingleRecord.Builder, com.znjt.proto.GPSSingleRecordOrBuilder>(
                gpsSingleRecord_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        gpsSingleRecord_ = null;
      }
      return gpsSingleRecordBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.znjt.proto.SyncMulSingleImgRequest)
  }

  // @@protoc_insertion_point(class_scope:com.znjt.proto.SyncMulSingleImgRequest)
  private static final com.znjt.proto.SyncMulSingleImgRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.znjt.proto.SyncMulSingleImgRequest();
  }

  public static com.znjt.proto.SyncMulSingleImgRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SyncMulSingleImgRequest>
      PARSER = new com.google.protobuf.AbstractParser<SyncMulSingleImgRequest>() {
    @java.lang.Override
    public SyncMulSingleImgRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SyncMulSingleImgRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SyncMulSingleImgRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncMulSingleImgRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.znjt.proto.SyncMulSingleImgRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

