// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transfer.proto

package com.znjt.proto;

/**
 * Protobuf type {@code com.znjt.proto.SyncDataRequest}
 */
public  final class SyncDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.znjt.proto.SyncDataRequest)
    SyncDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SyncDataRequest.newBuilder() to construct.
  private SyncDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SyncDataRequest() {
    dataType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SyncDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            dataType_ = rawValue;
            break;
          }
          case 18: {
            com.znjt.proto.INIRecord.Builder subBuilder = null;
            if (recordCase_ == 2) {
              subBuilder = ((com.znjt.proto.INIRecord) record_).toBuilder();
            }
            record_ =
                input.readMessage(com.znjt.proto.INIRecord.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.znjt.proto.INIRecord) record_);
              record_ = subBuilder.buildPartial();
            }
            recordCase_ = 2;
            break;
          }
          case 26: {
            com.znjt.proto.GPSRecord.Builder subBuilder = null;
            if (recordCase_ == 3) {
              subBuilder = ((com.znjt.proto.GPSRecord) record_).toBuilder();
            }
            record_ =
                input.readMessage(com.znjt.proto.GPSRecord.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.znjt.proto.GPSRecord) record_);
              record_ = subBuilder.buildPartial();
            }
            recordCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.znjt.proto.SyncDataRequest.class, com.znjt.proto.SyncDataRequest.Builder.class);
  }

  private int recordCase_ = 0;
  private java.lang.Object record_;
  public enum RecordCase
      implements com.google.protobuf.Internal.EnumLite {
    INI_RECORD(2),
    GPS_RECORD(3),
    RECORD_NOT_SET(0);
    private final int value;
    private RecordCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RecordCase valueOf(int value) {
      return forNumber(value);
    }

    public static RecordCase forNumber(int value) {
      switch (value) {
        case 2: return INI_RECORD;
        case 3: return GPS_RECORD;
        case 0: return RECORD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RecordCase
  getRecordCase() {
    return RecordCase.forNumber(
        recordCase_);
  }

  public static final int DATA_TYPE_FIELD_NUMBER = 1;
  private int dataType_;
  /**
   * <code>.com.znjt.proto.DataType data_type = 1;</code>
   */
  public int getDataTypeValue() {
    return dataType_;
  }
  /**
   * <code>.com.znjt.proto.DataType data_type = 1;</code>
   */
  public com.znjt.proto.DataType getDataType() {
    @SuppressWarnings("deprecation")
    com.znjt.proto.DataType result = com.znjt.proto.DataType.valueOf(dataType_);
    return result == null ? com.znjt.proto.DataType.UNRECOGNIZED : result;
  }

  public static final int INI_RECORD_FIELD_NUMBER = 2;
  /**
   * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
   */
  public boolean hasIniRecord() {
    return recordCase_ == 2;
  }
  /**
   * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
   */
  public com.znjt.proto.INIRecord getIniRecord() {
    if (recordCase_ == 2) {
       return (com.znjt.proto.INIRecord) record_;
    }
    return com.znjt.proto.INIRecord.getDefaultInstance();
  }
  /**
   * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
   */
  public com.znjt.proto.INIRecordOrBuilder getIniRecordOrBuilder() {
    if (recordCase_ == 2) {
       return (com.znjt.proto.INIRecord) record_;
    }
    return com.znjt.proto.INIRecord.getDefaultInstance();
  }

  public static final int GPS_RECORD_FIELD_NUMBER = 3;
  /**
   * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
   */
  public boolean hasGpsRecord() {
    return recordCase_ == 3;
  }
  /**
   * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
   */
  public com.znjt.proto.GPSRecord getGpsRecord() {
    if (recordCase_ == 3) {
       return (com.znjt.proto.GPSRecord) record_;
    }
    return com.znjt.proto.GPSRecord.getDefaultInstance();
  }
  /**
   * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
   */
  public com.znjt.proto.GPSRecordOrBuilder getGpsRecordOrBuilder() {
    if (recordCase_ == 3) {
       return (com.znjt.proto.GPSRecord) record_;
    }
    return com.znjt.proto.GPSRecord.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataType_ != com.znjt.proto.DataType.T_INI.getNumber()) {
      output.writeEnum(1, dataType_);
    }
    if (recordCase_ == 2) {
      output.writeMessage(2, (com.znjt.proto.INIRecord) record_);
    }
    if (recordCase_ == 3) {
      output.writeMessage(3, (com.znjt.proto.GPSRecord) record_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataType_ != com.znjt.proto.DataType.T_INI.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, dataType_);
    }
    if (recordCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.znjt.proto.INIRecord) record_);
    }
    if (recordCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.znjt.proto.GPSRecord) record_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.znjt.proto.SyncDataRequest)) {
      return super.equals(obj);
    }
    com.znjt.proto.SyncDataRequest other = (com.znjt.proto.SyncDataRequest) obj;

    boolean result = true;
    result = result && dataType_ == other.dataType_;
    result = result && getRecordCase().equals(
        other.getRecordCase());
    if (!result) return false;
    switch (recordCase_) {
      case 2:
        result = result && getIniRecord()
            .equals(other.getIniRecord());
        break;
      case 3:
        result = result && getGpsRecord()
            .equals(other.getGpsRecord());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + dataType_;
    switch (recordCase_) {
      case 2:
        hash = (37 * hash) + INI_RECORD_FIELD_NUMBER;
        hash = (53 * hash) + getIniRecord().hashCode();
        break;
      case 3:
        hash = (37 * hash) + GPS_RECORD_FIELD_NUMBER;
        hash = (53 * hash) + getGpsRecord().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.znjt.proto.SyncDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.SyncDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.SyncDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.SyncDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.SyncDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.znjt.proto.SyncDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.znjt.proto.SyncDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.znjt.proto.SyncDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.znjt.proto.SyncDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.znjt.proto.SyncDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.znjt.proto.SyncDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.znjt.proto.SyncDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.znjt.proto.SyncDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.znjt.proto.SyncDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.znjt.proto.SyncDataRequest)
      com.znjt.proto.SyncDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.znjt.proto.SyncDataRequest.class, com.znjt.proto.SyncDataRequest.Builder.class);
    }

    // Construct using com.znjt.proto.SyncDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dataType_ = 0;

      recordCase_ = 0;
      record_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.znjt.proto.TransferProto.internal_static_com_znjt_proto_SyncDataRequest_descriptor;
    }

    @java.lang.Override
    public com.znjt.proto.SyncDataRequest getDefaultInstanceForType() {
      return com.znjt.proto.SyncDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.znjt.proto.SyncDataRequest build() {
      com.znjt.proto.SyncDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.znjt.proto.SyncDataRequest buildPartial() {
      com.znjt.proto.SyncDataRequest result = new com.znjt.proto.SyncDataRequest(this);
      result.dataType_ = dataType_;
      if (recordCase_ == 2) {
        if (iniRecordBuilder_ == null) {
          result.record_ = record_;
        } else {
          result.record_ = iniRecordBuilder_.build();
        }
      }
      if (recordCase_ == 3) {
        if (gpsRecordBuilder_ == null) {
          result.record_ = record_;
        } else {
          result.record_ = gpsRecordBuilder_.build();
        }
      }
      result.recordCase_ = recordCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.znjt.proto.SyncDataRequest) {
        return mergeFrom((com.znjt.proto.SyncDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.znjt.proto.SyncDataRequest other) {
      if (other == com.znjt.proto.SyncDataRequest.getDefaultInstance()) return this;
      if (other.dataType_ != 0) {
        setDataTypeValue(other.getDataTypeValue());
      }
      switch (other.getRecordCase()) {
        case INI_RECORD: {
          mergeIniRecord(other.getIniRecord());
          break;
        }
        case GPS_RECORD: {
          mergeGpsRecord(other.getGpsRecord());
          break;
        }
        case RECORD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.znjt.proto.SyncDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.znjt.proto.SyncDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int recordCase_ = 0;
    private java.lang.Object record_;
    public RecordCase
        getRecordCase() {
      return RecordCase.forNumber(
          recordCase_);
    }

    public Builder clearRecord() {
      recordCase_ = 0;
      record_ = null;
      onChanged();
      return this;
    }


    private int dataType_ = 0;
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public Builder setDataTypeValue(int value) {
      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public com.znjt.proto.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.znjt.proto.DataType result = com.znjt.proto.DataType.valueOf(dataType_);
      return result == null ? com.znjt.proto.DataType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public Builder setDataType(com.znjt.proto.DataType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dataType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.znjt.proto.DataType data_type = 1;</code>
     */
    public Builder clearDataType() {
      
      dataType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.znjt.proto.INIRecord, com.znjt.proto.INIRecord.Builder, com.znjt.proto.INIRecordOrBuilder> iniRecordBuilder_;
    /**
     * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
     */
    public boolean hasIniRecord() {
      return recordCase_ == 2;
    }
    /**
     * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
     */
    public com.znjt.proto.INIRecord getIniRecord() {
      if (iniRecordBuilder_ == null) {
        if (recordCase_ == 2) {
          return (com.znjt.proto.INIRecord) record_;
        }
        return com.znjt.proto.INIRecord.getDefaultInstance();
      } else {
        if (recordCase_ == 2) {
          return iniRecordBuilder_.getMessage();
        }
        return com.znjt.proto.INIRecord.getDefaultInstance();
      }
    }
    /**
     * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
     */
    public Builder setIniRecord(com.znjt.proto.INIRecord value) {
      if (iniRecordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        record_ = value;
        onChanged();
      } else {
        iniRecordBuilder_.setMessage(value);
      }
      recordCase_ = 2;
      return this;
    }
    /**
     * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
     */
    public Builder setIniRecord(
        com.znjt.proto.INIRecord.Builder builderForValue) {
      if (iniRecordBuilder_ == null) {
        record_ = builderForValue.build();
        onChanged();
      } else {
        iniRecordBuilder_.setMessage(builderForValue.build());
      }
      recordCase_ = 2;
      return this;
    }
    /**
     * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
     */
    public Builder mergeIniRecord(com.znjt.proto.INIRecord value) {
      if (iniRecordBuilder_ == null) {
        if (recordCase_ == 2 &&
            record_ != com.znjt.proto.INIRecord.getDefaultInstance()) {
          record_ = com.znjt.proto.INIRecord.newBuilder((com.znjt.proto.INIRecord) record_)
              .mergeFrom(value).buildPartial();
        } else {
          record_ = value;
        }
        onChanged();
      } else {
        if (recordCase_ == 2) {
          iniRecordBuilder_.mergeFrom(value);
        }
        iniRecordBuilder_.setMessage(value);
      }
      recordCase_ = 2;
      return this;
    }
    /**
     * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
     */
    public Builder clearIniRecord() {
      if (iniRecordBuilder_ == null) {
        if (recordCase_ == 2) {
          recordCase_ = 0;
          record_ = null;
          onChanged();
        }
      } else {
        if (recordCase_ == 2) {
          recordCase_ = 0;
          record_ = null;
        }
        iniRecordBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
     */
    public com.znjt.proto.INIRecord.Builder getIniRecordBuilder() {
      return getIniRecordFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
     */
    public com.znjt.proto.INIRecordOrBuilder getIniRecordOrBuilder() {
      if ((recordCase_ == 2) && (iniRecordBuilder_ != null)) {
        return iniRecordBuilder_.getMessageOrBuilder();
      } else {
        if (recordCase_ == 2) {
          return (com.znjt.proto.INIRecord) record_;
        }
        return com.znjt.proto.INIRecord.getDefaultInstance();
      }
    }
    /**
     * <code>.com.znjt.proto.INIRecord ini_record = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.znjt.proto.INIRecord, com.znjt.proto.INIRecord.Builder, com.znjt.proto.INIRecordOrBuilder> 
        getIniRecordFieldBuilder() {
      if (iniRecordBuilder_ == null) {
        if (!(recordCase_ == 2)) {
          record_ = com.znjt.proto.INIRecord.getDefaultInstance();
        }
        iniRecordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.znjt.proto.INIRecord, com.znjt.proto.INIRecord.Builder, com.znjt.proto.INIRecordOrBuilder>(
                (com.znjt.proto.INIRecord) record_,
                getParentForChildren(),
                isClean());
        record_ = null;
      }
      recordCase_ = 2;
      onChanged();;
      return iniRecordBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.znjt.proto.GPSRecord, com.znjt.proto.GPSRecord.Builder, com.znjt.proto.GPSRecordOrBuilder> gpsRecordBuilder_;
    /**
     * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
     */
    public boolean hasGpsRecord() {
      return recordCase_ == 3;
    }
    /**
     * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
     */
    public com.znjt.proto.GPSRecord getGpsRecord() {
      if (gpsRecordBuilder_ == null) {
        if (recordCase_ == 3) {
          return (com.znjt.proto.GPSRecord) record_;
        }
        return com.znjt.proto.GPSRecord.getDefaultInstance();
      } else {
        if (recordCase_ == 3) {
          return gpsRecordBuilder_.getMessage();
        }
        return com.znjt.proto.GPSRecord.getDefaultInstance();
      }
    }
    /**
     * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
     */
    public Builder setGpsRecord(com.znjt.proto.GPSRecord value) {
      if (gpsRecordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        record_ = value;
        onChanged();
      } else {
        gpsRecordBuilder_.setMessage(value);
      }
      recordCase_ = 3;
      return this;
    }
    /**
     * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
     */
    public Builder setGpsRecord(
        com.znjt.proto.GPSRecord.Builder builderForValue) {
      if (gpsRecordBuilder_ == null) {
        record_ = builderForValue.build();
        onChanged();
      } else {
        gpsRecordBuilder_.setMessage(builderForValue.build());
      }
      recordCase_ = 3;
      return this;
    }
    /**
     * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
     */
    public Builder mergeGpsRecord(com.znjt.proto.GPSRecord value) {
      if (gpsRecordBuilder_ == null) {
        if (recordCase_ == 3 &&
            record_ != com.znjt.proto.GPSRecord.getDefaultInstance()) {
          record_ = com.znjt.proto.GPSRecord.newBuilder((com.znjt.proto.GPSRecord) record_)
              .mergeFrom(value).buildPartial();
        } else {
          record_ = value;
        }
        onChanged();
      } else {
        if (recordCase_ == 3) {
          gpsRecordBuilder_.mergeFrom(value);
        }
        gpsRecordBuilder_.setMessage(value);
      }
      recordCase_ = 3;
      return this;
    }
    /**
     * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
     */
    public Builder clearGpsRecord() {
      if (gpsRecordBuilder_ == null) {
        if (recordCase_ == 3) {
          recordCase_ = 0;
          record_ = null;
          onChanged();
        }
      } else {
        if (recordCase_ == 3) {
          recordCase_ = 0;
          record_ = null;
        }
        gpsRecordBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
     */
    public com.znjt.proto.GPSRecord.Builder getGpsRecordBuilder() {
      return getGpsRecordFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
     */
    public com.znjt.proto.GPSRecordOrBuilder getGpsRecordOrBuilder() {
      if ((recordCase_ == 3) && (gpsRecordBuilder_ != null)) {
        return gpsRecordBuilder_.getMessageOrBuilder();
      } else {
        if (recordCase_ == 3) {
          return (com.znjt.proto.GPSRecord) record_;
        }
        return com.znjt.proto.GPSRecord.getDefaultInstance();
      }
    }
    /**
     * <code>.com.znjt.proto.GPSRecord gps_record = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.znjt.proto.GPSRecord, com.znjt.proto.GPSRecord.Builder, com.znjt.proto.GPSRecordOrBuilder> 
        getGpsRecordFieldBuilder() {
      if (gpsRecordBuilder_ == null) {
        if (!(recordCase_ == 3)) {
          record_ = com.znjt.proto.GPSRecord.getDefaultInstance();
        }
        gpsRecordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.znjt.proto.GPSRecord, com.znjt.proto.GPSRecord.Builder, com.znjt.proto.GPSRecordOrBuilder>(
                (com.znjt.proto.GPSRecord) record_,
                getParentForChildren(),
                isClean());
        record_ = null;
      }
      recordCase_ = 3;
      onChanged();;
      return gpsRecordBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.znjt.proto.SyncDataRequest)
  }

  // @@protoc_insertion_point(class_scope:com.znjt.proto.SyncDataRequest)
  private static final com.znjt.proto.SyncDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.znjt.proto.SyncDataRequest();
  }

  public static com.znjt.proto.SyncDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SyncDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<SyncDataRequest>() {
    @java.lang.Override
    public SyncDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SyncDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SyncDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.znjt.proto.SyncDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

