// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transfer.proto

package com.znjt.proto;

public interface SyncMulSingleImgRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.znjt.proto.SyncMulSingleImgRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.znjt.proto.DataType data_type = 1;</code>
   */
  int getDataTypeValue();
  /**
   * <code>.com.znjt.proto.DataType data_type = 1;</code>
   */
  com.znjt.proto.DataType getDataType();

  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  java.util.List<com.znjt.proto.GPSSingleRecord> 
      getGpsSingleRecordList();
  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  com.znjt.proto.GPSSingleRecord getGpsSingleRecord(int index);
  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  int getGpsSingleRecordCount();
  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  java.util.List<? extends com.znjt.proto.GPSSingleRecordOrBuilder> 
      getGpsSingleRecordOrBuilderList();
  /**
   * <code>repeated .com.znjt.proto.GPSSingleRecord gps_single_record = 2;</code>
   */
  com.znjt.proto.GPSSingleRecordOrBuilder getGpsSingleRecordOrBuilder(
      int index);
}
